### ISSUE TITLE
[Warning from Xcode 15]: forming 'UnsafeMutableRawPointer' to a variable of type '(String) -> ()'; 

### ISSUE THREAD

**Issue by tinder-kaijing** [lyft/swift-index-store#54]
warning from Xcode 15.0 beta-8 on macOS 13.5.1
======================================

INFO: From Compiling Swift module @com_github_lyft_swift_index_store//:IndexStore:
external/com_github_lyft_swift_index_store/Sources/IndexStore/IndexStore.swift:49:67: warning: forming 'UnsafeMutableRawPointer' to a variable of type '(String) -> ()'; this is likely incorrect because '(String) -> ()' may contain an object reference.
        indexstore_store_units_apply_f(self.store, /*unsorted*/0, &context) { context, unitName in
                                                                  ^
external/com_github_lyft_swift_index_store/Sources/IndexStore/IndexStore.swift:176:66: warning: forming 'UnsafeMutableRawPointer' to a variable of type '(UnitReader, (UnitDependency) -> ())'; this is likely incorrect because '(UnitReader, (UnitDependency) -> ())' may contain an object reference.
        indexstore_unit_reader_dependencies_apply_f(self.reader, &context) { context, unitDependency in
                                                                 ^
external/com_github_lyft_swift_index_store/Sources/IndexStore/IndexStore.swift:235:80: warning: forming 'UnsafeMutableRawPointer' to a variable of type '(RecordReader, (Symbol) -> ())'; this is likely incorrect because '(RecordReader, (Symbol) -> ())' may contain an object reference.
        indexstore_record_reader_symbols_apply_f(self.reader, /*nocache*/true, &context) { context, symbol in
                                                                               ^
external/com_github_lyft_swift_index_store/Sources/IndexStore/IndexStore.swift:248:67: warning: forming 'UnsafeMutableRawPointer' to a variable of type '(RecordReader, (SymbolOccurrence) -> ())'; this is likely incorrect because '(RecordReader, (SymbolOccurrence) -> ())' may contain an object reference.
        indexstore_record_reader_occurrences_apply_f(self.reader, &context) { context, occurrence in
                                                                  ^
external/com_github_lyft_swift_index_store/Sources/IndexStore/IndexStore.swift:284:66: warning: forming 'UnsafeMutableRawPointer' to a variable of type '(SymbolOccurrence, (Symbol, SymbolRoles) -> ())'; this is likely incorrect because '(SymbolOccurrence, (Symbol, SymbolRoles) -> ())' may contain an object reference.
        indexstore_occurrence_relations_apply_f(self.occurrence, &context) { context, relation in
                                                                 ^

**Comment by keith** [comment]
Thanks, this is fixed in this release https://github.com/lyft/swift-index-store/releases/tag/1.5.0

**Comment by keith** [comment]
Thanks, this is fixed in this release https://github.com/lyft/swift-index-store/releases/tag/1.5.0

**Comment by tinder-kaijing** [comment]
Thanks very much!
