### ISSUE TITLE
Bzlmod support

### ISSUE THREAD

**Issue by erikkerber** [lyft/swift-index-store#55]
I think this is our last WORKSPACE dependency, would be great to have in the registry.

**Comment by keith** [comment]
https://github.com/lyft/swift-index-store/pull/58

**Comment by erikkerber** [comment]
lol I realized I should have said BCR to be specific else I could have done this myself 😂 

Sorry, and not urgent

**Comment by keith** [comment]
https://github.com/bazelbuild/bazel-central-registry/pull/1445

**Comment by erikkerber** [comment]
lol thakns a million 🙇🏼 🙇🏼
